"""initial model setup

Revision ID: 4ec1d5e39fa2
Revises: 
Create Date: 2024-11-30 17:19:13.622825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ec1d5e39fa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commissioner_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['commissioner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfl_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nfl_team_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nfl_team_id'], ['nfl_team.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fantasy_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfl_player_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opponent_id'], ['nfl_team.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['nfl_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_settings',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('qb', sa.Integer(), nullable=False),
    sa.Column('rb', sa.Integer(), nullable=False),
    sa.Column('wr', sa.Integer(), nullable=False),
    sa.Column('te', sa.Integer(), nullable=False),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('scoring_settings',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('pass_tds', sa.Float(), nullable=False),
    sa.Column('pass_yds', sa.Float(), nullable=False),
    sa.Column('rush_tds', sa.Float(), nullable=False),
    sa.Column('rush_yds', sa.Float(), nullable=False),
    sa.Column('pass_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('rush_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('rec_tds', sa.Float(), nullable=False),
    sa.Column('rec_yds', sa.Float(), nullable=False),
    sa.Column('rec_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('other_tds', sa.Float(), nullable=False),
    sa.Column('fumbles', sa.Float(), nullable=False),
    sa.Column('def_tds', sa.Float(), nullable=False),
    sa.Column('def_pts', sa.Float(), nullable=False),
    sa.Column('xp_ret_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('ints', sa.Float(), nullable=False),
    sa.Column('sacks', sa.Float(), nullable=False),
    sa.Column('fumble_rec', sa.Float(), nullable=False),
    sa.Column('pts_against_0', sa.Float(), nullable=False),
    sa.Column('pts_against_1_14', sa.Float(), nullable=False),
    sa.Column('pts_against_15_21', sa.Float(), nullable=False),
    sa.Column('pts_against_22_28', sa.Float(), nullable=False),
    sa.Column('pts_against_29_35', sa.Float(), nullable=False),
    sa.Column('pts_against_35_plus', sa.Float(), nullable=False),
    sa.Column('fg', sa.Float(), nullable=False),
    sa.Column('fg_40', sa.Float(), nullable=False),
    sa.Column('fg_50', sa.Float(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('defensive_player_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('def_tds', sa.Float(), nullable=False),
    sa.Column('def_pts', sa.Float(), nullable=False),
    sa.Column('def_xp_ret_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('ints', sa.Float(), nullable=False),
    sa.Column('sacks', sa.Float(), nullable=False),
    sa.Column('fumble_rec', sa.Float(), nullable=False),
    sa.Column('pts_against_0', sa.Float(), nullable=False),
    sa.Column('pts_against_1_14', sa.Float(), nullable=False),
    sa.Column('pts_against_15_21', sa.Float(), nullable=False),
    sa.Column('pts_against_22_28', sa.Float(), nullable=False),
    sa.Column('pts_against_29_35', sa.Float(), nullable=False),
    sa.Column('pts_against_35_plus', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_player_game.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('kicker_player_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('fg', sa.Float(), nullable=False),
    sa.Column('fg_40', sa.Float(), nullable=False),
    sa.Column('fg_50', sa.Float(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_player_game.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('offensive_player_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('pass_tds', sa.Float(), nullable=False),
    sa.Column('rush_tds', sa.Float(), nullable=False),
    sa.Column('rush_Tsds', sa.Float(), nullable=False),
    sa.Column('pass_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('rush_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('rec_tds', sa.Float(), nullable=False),
    sa.Column('rec_yds', sa.Float(), nullable=False),
    sa.Column('rec_two_pt_conv', sa.Float(), nullable=False),
    sa.Column('other_tds', sa.Float(), nullable=False),
    sa.Column('fumbles', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_player_game.id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('roster_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_team_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('nfl_player_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_team_id'], ['fantasy_team.id'], ),
    sa.ForeignKeyConstraint(['nfl_player_game_id'], ['nfl_player_game.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_slot')
    op.drop_table('offensive_player_stats')
    op.drop_table('kicker_player_stats')
    op.drop_table('defensive_player_stats')
    op.drop_table('scoring_settings')
    op.drop_table('roster_settings')
    op.drop_table('nfl_player_game')
    op.drop_table('fantasy_team')
    op.drop_table('nfl_player')
    op.drop_table('league')
    op.drop_table('users')
    op.drop_table('position')
    op.drop_table('nfl_team')
    # ### end Alembic commands ###
