"""updated scoring settings ot match LSS

Revision ID: 711f54871a44
Revises: c5bf5156c72c
Create Date: 2024-12-04 00:40:29.844769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '711f54871a44'
down_revision: Union[str, None] = 'c5bf5156c72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defensive_player_stats', sa.Column('pts_against_1_6', sa.Float(), nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_7_13', sa.Float(), nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_14_20', sa.Float(), nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_21_27', sa.Float(), nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_28_34', sa.Float(), nullable=False))
    op.drop_column('defensive_player_stats', 'pts_against_29_35')
    op.drop_column('defensive_player_stats', 'pts_against_1_14')
    op.drop_column('defensive_player_stats', 'pts_against_15_21')
    op.drop_column('defensive_player_stats', 'pts_against_22_28')
    op.add_column('offensive_player_stats', sa.Column('pass_yds', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('pass_cmp', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('pass_att', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('rush_att', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('rush_yds', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('targets', sa.Float(), nullable=False))
    op.add_column('offensive_player_stats', sa.Column('recs', sa.Float(), nullable=False))
    op.drop_column('offensive_player_stats', 'rush_Tsds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offensive_player_stats', sa.Column('rush_Tsds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('offensive_player_stats', 'recs')
    op.drop_column('offensive_player_stats', 'targets')
    op.drop_column('offensive_player_stats', 'rush_yds')
    op.drop_column('offensive_player_stats', 'rush_att')
    op.drop_column('offensive_player_stats', 'pass_att')
    op.drop_column('offensive_player_stats', 'pass_cmp')
    op.drop_column('offensive_player_stats', 'pass_yds')
    op.add_column('defensive_player_stats', sa.Column('pts_against_22_28', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_15_21', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_1_14', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('defensive_player_stats', sa.Column('pts_against_29_35', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('defensive_player_stats', 'pts_against_28_34')
    op.drop_column('defensive_player_stats', 'pts_against_21_27')
    op.drop_column('defensive_player_stats', 'pts_against_14_20')
    op.drop_column('defensive_player_stats', 'pts_against_7_13')
    op.drop_column('defensive_player_stats', 'pts_against_1_6')
    # ### end Alembic commands ###
