"""added dst to model

Revision ID: 8e0be8caaa8a
Revises: 711f54871a44
Create Date: 2024-12-04 02:26:05.429180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e0be8caaa8a'
down_revision: Union[str, None] = '711f54871a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roster_settings', sa.Column('dst', sa.Integer(), nullable=False))
    op.alter_column('roster_slot', 'nfl_player_game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roster_slot', 'nfl_player_game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('roster_settings', 'dst')
    # ### end Alembic commands ###
